#!/bin/sh

if [ ! -d testscripts ]; then
   echo "Unable to find test scripts"
fi

if [ -z $1 ]; then
    echo "Usage: $0 basedir"
    exit 1
fi

BASEDIR=$1
SERVICEDIR=$BASEDIR/services

mkdir -p $SERVICEDIR
mkfifo $BASEDIR/in
mkfifo $BASEDIR/out
cp -R testscripts $BASEDIR

genservice(){
    SVTYPE=$1
    SVNUM=$2
    for i in `seq $SVNUM`; do
        SERVICE=$SERVICEDIR/$SVTYPE$i
        mkdir -p $SERVICE
        if [ $SVTYPE = "disabled" ]; then
            touch $SERVICE/noauto
        fi
        cat > $SERVICE/run <<EOF
#!/bin/sh
exec `readlink -f $BASEDIR/testscripts/$SVTYPE` $i
EOF
        chmod +x $SERVICE/run
    done
}

# a bunch of scripts exiting immediately
genservice defunct 3
# a bunch of scripts disabled by default
genservice disabled 2
# a bunch of scripts running normally
genservice normal 1
# a bunch of scripts ignoring SIGTERM
#genservice termign 2

export ASVM_BASEDIR=$BASEDIR

./asvm > asvm.log &
echo "Log is in asvm.log, kill asvm at $! when you're done"
echo "Do export ASVM_BASEDIR=$BASEDIR before you use svc"