#!/bin/sh
#
# $Id: mktestdir,v 1.1 2008-05-09 18:23:19 bwachter Exp $
# * $Log: mktestdir,v $
# * Revision 1.1  2008-05-09 18:23:19  bwachter
# * a script to generate a directory with sample services
# *
#

if [ ! -d testscripts ]; then
   echo "Unable to find test scripts"
fi

BASEDIR=/tmp/etc/asvm
SERVICEDIR=$BASEDIR/services

mkdir -p $SERVICEDIR
mkfifo $BASEDIR/in
mkfifo $BASEDIR/out
cp -R testscripts $BASEDIR

genservice(){
	SVTYPE=$1
	SVNUM=$2
	for i in `seq $SVNUM`; do
	    SERVICE=$SERVICEDIR/$SVTYPE$i
	    mkdir -p $SERVICE
	    if [ $SVTYPE = "disabled" ]; then
	       touch $SERVICE/noauto
	    fi
	    cat > $SERVICE/run <<EOF
#!/bin/sh
exec $BASEDIR/testscripts/defunct $i
EOF
	    chmod +x $SERVICE/run
	done
}

# a bunch of scripts exiting immediately
genservice defunct 3
# a bunch of scripts disabled by default
genservice disabled 2
# a bunch of scripts running normally
genservice normal 1
# a bunch of scripts ignoring SIGTERM
genservice termign 2 